Import libraries

In [1]:
import pandas as pd
import numpy as np
from random import randint

Construct data

In [2]:
x1 = np.array([randint(100, 999) for i in range(0,1000)])
x2 = np.array([randint(100, 999) for i in range(0,1000)])
x3 = np.array([randint(100, 999) for i in range(0,1000)])
x4 = np.array([randint(100, 999) for i in range(0,1000)])
x5 = np.array([randint(100, 999) for i in range(0,1000)])

bias = np.ones(1000).astype(int)
y    = np.array([randint(0,1) for i in range(0,1000)])

In [3]:
x1 = np.reshape(x1 , (len(x1), 1))
x2 = np.reshape(x2 , (len(x2), 1))
x3 = np.reshape(x3 , (len(x3), 1))
x4 = np.reshape(x4 , (len(x4), 1))
x5 = np.reshape(x5 , (len(x5), 1))

bias = np.reshape(bias , (len(bias), 1))
y    = np.reshape(y , (len(y), 1))

In [4]:
X = np.append(bias , x1 , axis = 1)
X = np.append(X , x2 , axis = 1)
X = np.append(X , x3 , axis = 1)
X = np.append(X , x4 , axis = 1)
X = np.append(X , x5 , axis = 1)

X[:5]

array([[  1, 163, 599, 770, 444, 622],
       [  1, 121, 380, 961, 683, 588],
       [  1, 335, 517, 149, 661, 345],
       [  1, 753, 788, 134, 397, 324],
       [  1, 618, 263, 199, 228, 442]])

Hypothesis

In [5]:
rows , cols = X.shape

print('\nrows: ',rows , '\n cols: ', cols)


rows:  1000 
 cols:  6


In [6]:
theta = np.zeros(cols).astype(int)

theta = np.reshape(theta, (cols, 1))

theta

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [7]:
def logreg_hyp(theta , x):
    
    return np.dot(theta , x)

Sigmoid

In [8]:
def sigmoid(z):
    
    return 1 / (1 + np.exp(-z))

Cost function

In [9]:
def cost_compute(theta , x , y):
    
    cost = (y*(np.log(sigmoid(logreg_hyp(x , theta))))) + ((1-y)*(np.log(1 - sigmoid(logreg_hyp(x , theta)))))
    
    l    = np.sum(cost) / -rows
    
    return l

In [10]:
cost_compute(theta , X , y)

0.6931471805599454

Gradient descent

In [11]:
def gradient_descent(theta , x , y , alpha , iterations):
    
    for i in range(iterations):
        
        residual = sigmoid(logreg_hyp(x , theta)) - y
        gradient = np.dot(x.transpose() , residual) / rows
        
        theta    = theta - (alpha/rows) * gradient
        
        return theta

In [12]:
theta = gradient_descent(theta = theta , x = X , y = y , alpha = 0.00001 , iterations = 5000000000)

In [13]:
theta

array([[ 1.00000e-10],
       [-4.25950e-08],
       [ 1.14665e-07],
       [-1.84750e-08],
       [ 4.36350e-08],
       [ 1.09800e-08]])

In [14]:
cost_compute(theta , X , y)

0.6931454483131277