In [1]:
import pandas as pd
import numpy as np
from random import randint

In [2]:
# np.arrays 
x1   = np.array([randint(100,999) for i in range(0,10)])
x2   = np.array([randint(100,999) for i in range(0,10)])
x3   = np.array([randint(100,999) for i in range(0,10)])
x4   = np.array([randint(100,999) for i in range(0,10)])
x5   = np.array([randint(100,999) for i in range(0,10)])

bias = np.ones(10).astype(int)
y    = np.array([randint(10,99) for i in range(0,10)])

print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(bias)
print(y)

[306 841 567 509 584 143 879 606 125 239]
[947 974 753 216 719 955 728 262 247 883]
[614 993 415 588 204 437 829 663 482 177]
[924 612 874 730 666 686 412 331 618 951]
[109 770 499 950 701 310 321 806 173 391]
[1 1 1 1 1 1 1 1 1 1]
[97 19 11 20 10 78 61 78 41 58]


In [3]:
# reshape np.arrays to matrix
x1   = np.reshape(x1,   (len(x1), 1))
x2   = np.reshape(x2,   (len(x2), 1))  
x3   = np.reshape(x3,   (len(x3), 1))  
x4   = np.reshape(x4,   (len(x4), 1))  
x5   = np.reshape(x5,   (len(x5), 1))  

bias = np.reshape(bias, (len(bias), 1))  
y    = np.reshape(y,    (len(y), 1))  

In [4]:
X = np.append(x1 , x2 , axis = 1)

X = np.append(X , x3 , axis = 1)
X = np.append(X , x4 , axis = 1)
X = np.append(X , x5 , axis = 1)
X = np.append(X ,bias, axis = 1)

X

array([[306, 947, 614, 924, 109,   1],
       [841, 974, 993, 612, 770,   1],
       [567, 753, 415, 874, 499,   1],
       [509, 216, 588, 730, 950,   1],
       [584, 719, 204, 666, 701,   1],
       [143, 955, 437, 686, 310,   1],
       [879, 728, 829, 412, 321,   1],
       [606, 262, 663, 331, 806,   1],
       [125, 247, 482, 618, 173,   1],
       [239, 883, 177, 951, 391,   1]])

X transpose x inverse

In [5]:
np.linalg.inv(X.transpose().dot(X))

array([[ 4.69453369e-06, -1.55105059e-06, -1.80964929e-06,
         1.95792469e-06, -2.25053876e-06, -4.38762916e-04],
       [-1.55105059e-06,  2.23796379e-06, -5.25901534e-08,
        -2.02423045e-06,  1.21924517e-06,  4.09094599e-05],
       [-1.80964929e-06, -5.25901534e-08,  3.29510735e-06,
         1.29682262e-06,  6.72341716e-07, -2.09696103e-03],
       [ 1.95792469e-06, -2.02423045e-06,  1.29682262e-06,
         5.85753807e-06, -6.86264211e-07, -3.92743401e-03],
       [-2.25053876e-06,  1.21924517e-06,  6.72341716e-07,
        -6.86264211e-07,  2.68513551e-06, -9.81797907e-04],
       [-4.38762916e-04,  4.09094599e-05, -2.09696103e-03,
        -3.92743401e-03, -9.81797907e-04,  4.58206724e+00]])

X Transpose Y

In [6]:
X.transpose().dot(y)

array([[198946],
       [330833],
       [263187],
       [317084],
       [193102],
       [   473]])

Finding coefficients

In [7]:
theta = np.linalg.inv(X.transpose().dot(X)).dot(X.transpose().dot(y))

theta

array([[-7.67479922e-02],
       [ 3.09136864e-02],
       [ 3.89780380e-02],
       [-7.17177691e-02],
       [-3.09063220e-02],
       [ 1.06755367e+02]])

In [8]:
beta_0 = theta[-1]
beta_1 = theta[0]
beta_2 = theta[1]
beta_3 = theta[2]
beta_4 = theta[3]
beta_5 = theta[4]

print(
    '\t beta_0: ', beta_0[0], '\n',
    '\t beta_1: ', beta_1[0], '\n',
    '\t beta_2: ', beta_2[0], '\n',
    '\t beta_3: ', beta_3[0], '\n',
    '\t beta_4: ', beta_4[0], '\n',
    '\t beta_5: ', beta_5[0], '\n',
)

	 beta_0:  106.75536740585721 
 	 beta_1:  -0.07674799222741124 
 	 beta_2:  0.030913686441630332 
 	 beta_3:  0.038978038008750215 
 	 beta_4:  -0.07171776910125294 
 	 beta_5:  -0.030906322046407142 



In [9]:
x1 = np.array([randint(100,999) for i in range(0, 5)])
x2 = np.array([randint(100,999) for i in range(0, 5)])
x3 = np.array([randint(100,999) for i in range(0, 5)])
x4 = np.array([randint(100,999) for i in range(0, 5)])
x5 = np.array([randint(100,999) for i in range(0, 5)])

In [9]:
def linear_regression(x1,x2,x3,x4,x5):
    
    beta_0 = 106.75536740585721
    beta_1 = -0.07674799222741124
    beta_2 = 0.030913686441630332
    beta_3 = 0.038978038008750215
    beta_4 = -0.07171776910125294
    beta_5 = -0.030906322046407142
    
    y = beta_0 + beta_1*x1 + beta_2*x2 + beta_3*x3 + beta_4*x4
    
    return y

In [11]:
y = linear_regression(x1,x2,x3,x4,x5)

y

array([[70.21103953],
       [67.13415359],
       [40.01181728],
       [44.93311054],
       [44.34896603],
       [93.13798808],
       [64.56411861],
       [70.44932759],
       [79.26338194],
       [54.4048967 ]])

In [12]:
np.reshape(y, (1, len(y)))

array([[70.21103953, 67.13415359, 40.01181728, 44.93311054, 44.34896603,
        93.13798808, 64.56411861, 70.44932759, 79.26338194, 54.4048967 ]])